packages:
  - name: joke
    actions:
      - name: joke
        runtime: 'python:default'
        web: true
        environment:
          DATABASE_URL: "mongodb-do-function-test-6c227d6b.mongo.ondigitalocean.com"
          DATABASE_USER: "doadmin"
          DATABASE_NAME: "myriad"
          DATABASE_PASSWORD: "2Y7x5o01z4b3OpN6"
        limits:
          timeout: 900000
          memory: 256