packages:
  - name: joke
    actions:
      - name: joke
        runtime: "python:default"
        environment:
          MONGO_URI: "${MONGO_URI}"
        limits:
          timeout: 900000
          memory: 256